### ISSUE TITLE
RFE: provide ALT+ key bindings on common buttons (OK, Cancel, Save, etc.)

### ISSUE THREAD

**Issue by sphakka** [sixsixfive/Glare#5]
What about adding those terribly useful (I'm a keyboard monkey ;-)) key bindings on common dialog windows' buttons, such as 'OK' (ALT+o), 'Save' (ALT+s), 'Cancel' (ALT+c), etc?

**Comment by sixsixfive** [comment]
see the settings files 

https://github.com/sixsixfive/Glare/blob/master/GlareYang/gtk-2.0/settings.ini
https://github.com/sixsixfive/Glare/blob/master/GlareYang/gtk-3.18/settings.ini

(eg change gtk-enable-mnemonics to 1)

https://developer.gnome.org/gtk2/stable/GtkSettings.html#GtkSettings.properties
https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings.properties

also note that this might not work for GTK3 since they removed nearly all keyboard support

**Comment by sphakka** [comment]
Thanks fort the tip! Indeed, it doesn't work for GTK3 -- all those settings are either dropped or deprecated :-( As I still have a mixed GTK system, I managed to set it for GTK2...
